openapi: 3.0.1
info:
  title: Realestate Search Plugin
  description: A plugin that allows the user to search for an ideal apartment using ChatGPT.
  version: 'v1'
servers:
  - url: https://openai-realestate-search.onrender.com
paths:
  /:
    get:
      operationId: getApartments
      summary: |
        Get a list of available apartments in the area the user is searching. After the response, you can view more results from the same search.
      parameters:
        - name: query
          in: query
          required: true
          content:
            application/json:
              schema:
                type: object
                properties:
                  channel:
                    type: string
                    description: Set to rent or buy depending on whether user wants to search for rental properties or houses to buy
                    default: rent
                  localities:
                    type: array
                    items:
                      type: object
                      properties:
                        subdivision:
                          type: string
                          description: State user is searching for properties in
                          default: NSW
                        postcode:
                          type: string
                          description: Postcode user is searching for properties in
                          default: 2287
                        searchLocation:
                          type: string
                          description: Location user is searching for properties in, formatted as "STATE POSTCODE" e.g. NSW 2287
                          default: NSW 2287
                  pageSize:
                    type: string
                    description: How many listings per page user is requesting
                    default: 20
                  page:
                    type: string
                    description: What page number user is requesting
                    default: 1
                  filters:
                    type: object
                    properties:
                      propertyTypes:
                        type: array
                        items:
                          type: string
                          description: A type of property the user is looking for
                          default: house
                      priceRange:
                        type: object
                        properties:
                          minimum:
                            type: string
                            description: Minimum price of the property
                            default: 200
                          maximum:
                            type: string
                            description: Maximum price of the property
                            default: 600
                      surroundingSuburbs:
                        type: boolean
                        description: Whether to search for surrounding suburbs
                        default: true
                      replaceProjectWithFirstChild:
                        type: boolean
                        default: false
        - in: query
          name: images
          schema:
            type: integer
          required: false
          description: Set to 0 to disable image results or any other number to set how many images per result to return. Default value is 2
      responses:
        "200":
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/getApartmentsResponse'
        "404":
          description: Not Found
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
                    description: The reason the request was rejected
components:
  schemas:
    getApartmentsResponse:
      type: object
      properties:
        totalListings:
          type: number
          description: Total number of property listings. You can also use this to work out how many more pages there are to navigate through by dividing the totalListings number by the number of listings per page
        currentPage:
          type: number
          description: The current page number
        pageSize:
          type: number
          description: The number of listings per page
        results:
          type: array
          items:
            type: object
            properties:
              prettyUrl:
                type: string
              description:
                type: string
              title:
                type: string
              features:
                type: object
                properties:
                  general:
                    type: object
                    properties:
                      bedrooms:
                        type: number
                      bathrooms:
                        type: number
                      parkingSpaces:
                        type: number
              price:
                type: object
                properties:
                  display:
                    type: string
              propertyType:
                type: string
              address:
                type: object
                properties:
                  streetAddress:
                    type: string
                  postcode:
                    type: string
                  suburb:
                    type: string
                  postCode:
                    type: string
                  location:
                    type: object
                    properties:
                      latitude:
                        type: number
                      longitude:
                        type: number
                  state:
                    type: string
              propertyFeatures:
                type: array
                items:
                  type: object
                  properties:
                    features:
                      type: array
                      items:
                        type: string
                    section:
                      type: string
                    label:
                      type: string
              bond:
                type: object
                properties:
                  display:
                    type: string
                  value:
                    type: number
              dateAvailable:
                type: object
                properties:
                  date:
                    type: string
              inspectionsAndAuctions:
                type: array
                items:
                  type: object
              generalFeatures:
                type: object
                properties:
                  bedrooms:
                    type: object
                    properties:
                      label:
                        type: string
                      type:
                        type: string
                      value:
                        type: number
                  bathrooms:
                    type: object
                    properties:
                      label:
                        type: string
                      type:
                        type: string
                      value:
                        type: number
                  parkingSpaces:
                    type: object
                    properties:
                      label:
                        type: string
                      type:
                        type: string
                      value:
                        type: number